#!/usr/bin/env python3
# Regenerates embedded.h from kernel.cl, sha512_consts.h and english.txt.
# The generated file is committed, so building needs only a C compiler.
import hashlib, os
os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
words = open("english.txt").read().split("\n")[:2048]
raw = open("english.txt", "rb").read()
assert len(words) == 2048 and hashlib.sha256(raw).hexdigest() == "2f5eed53a4727b4bf8880d8f3f199efc90e58503646d9ff8eff3a2ed3b24dbda"
src = open("sha512_consts.h").read() + "\n" + open("kernel.cl").read()
def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '\\n"'
out = ["// Generated by tools/embed.py from kernel.cl, sha512_consts.h and english.txt. Do not edit.",
       "#pragma once", "",
       "// OpenCL source as separate lines (MSVC limits the length of one string literal)",
       "static const char *const KERNEL_SRC[] = {"]
out += ["    " + cstr(l) + "," for l in src.split("\n")]
out += ["};", "#define KERNEL_SRC_LINES (sizeof(KERNEL_SRC) / sizeof(KERNEL_SRC[0]))", "",
        "// BIP-0039 English wordlist (sha256 2f5eed53...dbda)", "static const char *const WORDS[2048] = {"]
for i in range(0, 2048, 8):
    out.append("    " + " ".join('"%s",' % w for w in words[i:i + 8]))
out += ["};", ""]
open("embedded.h", "w").write("\n".join(out))
print("embedded.h:", len(src.split("\n")), "kernel lines, 2048 words")
